version: '3.8'

services:
  db-pagamento:
    image: postgres:16
    container_name: db-pagamento
    environment:
      POSTGRES_DB: mspagamento
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5433:5432"
    volumes:
      - pgdata-pagamento:/var/lib/postgresql/data
    networks:
      - pagamento-net

  app-pagamento:
    image: rseite/postech-mspagamento:1.0
    container_name: app-pagamento
    depends_on:
      - db-pagamento
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-pagamento:5432/mspagamento
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    networks:
      - pagamento-net

volumes:
  pgdata-pagamento:

networks:
  pagamento-net:
